### ISSUE TITLE
Not working when using Nvidia Freestyle.

### ISSUE THREAD

**Issue by Ninjaman349** [tmarenko/GenshinImpact_PaimonShutUp#12]
Hello. I use this app with Nvidia Freestyle over my game which is essentially Nvidia's Reshade. The filters I use alter the game's appearance using shaders to change color, contrast and adds bloom etc. When these filters are applied, the app's detection of Paimon's name starts to fail which is understandable in extreme cases, however the detection fails from very slight color changes due to bloom or saturation which would display over the UI. I've had to unfortunately change my Freestyle preset around this in order to keep the app working. Even as I still have it, the app still mutes and unmutes rather frequently and inconsistently when her name appears in dialogue. Is there a way we could adjust the color to detect or change the way Paimon's name is spotted so the app continues to mute in these circumstances? No setting in the current config works unfortunately.

**Comment by tmarenko** [comment]
Currently, these values are hardcoded:
https://github.com/tmarenko/GenshinImpact_PaimonShutUp/blob/70ae5df91f507c8f0a13e5c8fe521c064cbba8b1/source/main.cpp#L42-L43

You could fork the repository and compile the app with your own values ([I have an automatic workflow for this!](https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/workflows/build.yml)). 
Moving them to a configuration file is possible, but explaining how to set these values properly is a big concern. For the average user, it would be challenging to explain how to select the low and high color values, especially in BGR format.
