### ISSUE TITLE
I dont know if it is working or not

### ISSUE THREAD

**Issue by yamcris** [tmarenko/GenshinImpact_PaimonShutUp#13]
When I run the GenshinImpact_PaimonShutUp and open the game it closes and i keep hearing her. Am i doing it wrong or its not working? I dont know anything about programming so...

**Comment by tmarenko** [comment]
Usually you should see something like this:
![image](https://github.com/tmarenko/GenshinImpact_PaimonShutUp/assets/31345208/e068f79c-72a4-4531-a54d-213d13460234)

If it closes then there is probably some error. Try to execute the app from the command line (so you could see the output even if the window is closed). Here is an [example tutorial](https://www.indeed.com/career-advice/career-development/how-to-run-program-in-command-prompt), basically you need to:
- run "cmd"
- "cd" to the app directory
- run "GenshinImpact_PaimonShutUp.exe" in _cmd_ window

Here is an example how I did this:
![image](https://github.com/tmarenko/GenshinImpact_PaimonShutUp/assets/31345208/9023e8e1-964e-4310-98f6-2e429aaa5d89)

**Comment by yamcris** [comment]
Thank you, it started working the day after without doing nothing, but if it doesn't work again i will try this, also thank you for creating it now my game got totally better!
