### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by monte91** [tmarenko/GenshinImpact_PaimonShutUp#6]
Just saw this and it seemed amazing, but unfortunetly it dosn''t work. It just says ready for paimon and game closed when i close the game. Maybe the game files blocked it or something, any tips? win10, 3080ti, running in fullscreen/windowed  with 1 monitor.

**Comment by tmarenko** [comment]
What's your in-game screen resolution?

**Comment by monte91** [comment]
3,840 by 2,160

**Comment by monte91** [comment]
i evn tried 1080p windowed still nothing

**Comment by tmarenko** [comment]
What's language for text/UI are you using in the game? Script only works for eng version e.g. when Paimon's name is Paimon

**Comment by tmarenko** [comment]
Tested latest [release](https://github.com/tmarenko/GenshinImpact_PaimonShutUp/releases/tag/1.1.1) and it works for me. Win10, 3070, fullscreen 1 monitor at 1080p, eng language
![image](https://user-images.githubusercontent.com/31345208/185848753-b70d6206-700c-49d8-9fb0-87b577768215.png)

**Comment by monte91** [comment]
i'ts english and using 1 monitor

**Comment by monte91** [comment]
I tried 1080p full/win, taking off admin access/re adding it, maybe i need a set of drivers for the program?

**Comment by tmarenko** [comment]
No, it should work with default DirectX capture. Script probably can't capture the game properly or fails to recognize Paimon's name in cutscenes.
I can make a debug version of the script in order to find out what's happening. If you want to test it

**Comment by monte91** [comment]
I would appreciate it, thank you.

**Comment by tmarenko** [comment]
I've added debug branch: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/compare/main...debug
Build: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/2922618159
Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/7969356444/artifacts/340753519

Run it while talking to any NPC or Paimon (for example you can spawn her in your Serenitea Pot)
When you run exe file you should see a debug window like this:
![image](https://user-images.githubusercontent.com/31345208/186533610-b1d8029a-9875-4112-9c4f-8f131cb31682.png)

On top left you can see a cropped image that goes into OCR. 
Somewhere in the middle you can see red and green rectangle. Usually one of them should contain NPC's name.

Also, debug window copies it's data to `debug.png` file as well.

**Comment by tmarenko** [comment]
Also please try this build
https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/2922700683
Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/7969564015/artifacts/340765734

It uses `BitBlt` function instead of `PrintWindow` to capture game image

**Comment by monte91** [comment]
> Also please try this build https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/2922700683 Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/7969564015/artifacts/340765734
> 
> It uses `BitBlt` function instead of `PrintWindow` to capture game image

It didn't cap the name
![debug](https://user-images.githubusercontent.com/25239241/186562673-5548f408-1f4f-4381-8f2e-1f6e9260a314.png)

**Comment by tmarenko** [comment]
Check your display settings in Windows. Do you have more than 100% scale? If so try with 100%
![image](https://user-images.githubusercontent.com/31345208/186649530-b2b044e2-2ca0-4e9e-a517-59edec09de52.png)

> I've added debug branch: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/compare/main...debug
Build: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/2922618159
Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/7969356444/artifacts/340753519

Did the first build work for you?

**Comment by monte91** [comment]
I used the 2nd build and it works, but is there a way to configure it to work with 200% scaling?

**Comment by tmarenko** [comment]
Yes, it's possible to make an application DPI aware so it'll properly capture with any scale.
Already made required changes: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/compare/main...dpi_aware
Build (in progress, need to wait): https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/2926759286

**Comment by monte91** [comment]
Cool, thank you

**Comment by tmarenko** [comment]
Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/7979797769/artifacts/341497334
Let me know if it works for you

**Comment by monte91** [comment]
yay it works, do you have a patreon or something?

**Comment by tmarenko** [comment]
Fix released in https://github.com/tmarenko/GenshinImpact_PaimonShutUp/releases/tag/1.2.0

> yay it works, do you have a patreon or something?

Hah, no, I don't =) happy to help you
