### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by noRynx** [tmarenko/GenshinImpact_PaimonShutUp#9]
says ready for paimon but actually doesnt mute the bitch

i have dual monitor setup playing on 1920x1080 fullscreen is it maybe for some reason trying to detect paimon in my 2nd monitor instead of the main one

**Comment by tmarenko** [comment]
I've built fresh debug build for you: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/3199387849
Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/8652205399/artifacts/389128258

Try it out, it should show you a preview of the game capture. Similar to this comment: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/issues/6#issuecomment-1226536296

>maybe for some reason trying to detect paimon in my 2nd monitor instead of the main one

Script captures directly from graphic process so it shouldn't matter on which monitor game is located

**Comment by noRynx** [comment]
> I've built fresh debug build for you: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/3199387849 Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/8652205399/artifacts/389128258
> 
> Try it out, it should show you a preview of the game capture. Similar to this comment: [#6 (comment)](https://github.com/tmarenko/GenshinImpact_PaimonShutUp/issues/6#issuecomment-1226536296)
> 
> > maybe for some reason trying to detect paimon in my 2nd monitor instead of the main one
> 
> Script captures directly from graphic process so it shouldn't matter on which monitor game is located

uhh its just straight up black screen
![image](https://user-images.githubusercontent.com/47905589/194412471-cac46f9c-c057-4a4f-8400-ceae75b45995.png)

and yea i checked the previous issue someone had but they just have the boxes misaligned while im just straight up empty

edit : it showed my desktop when i tried to first open the debug tab but when i tab back in the game it disappears

**Comment by noRynx** [comment]
oh nvm lol i was supposed to run it in the middle of the dialogue
![image](https://user-images.githubusercontent.com/47905589/194413569-7266c15a-3aa7-47c1-ad5b-1c1bf5468da8.png)

edit: is it cuz im playing on controller? gonna try keyboard

edit edit : well keyboard didnt do shyt either

**Comment by tmarenko** [comment]
Well it seems a bit off because usually it supposed to be in the green box.
Does it show anything it the black box in the top left corner?
Example: 
![image](https://user-images.githubusercontent.com/31345208/194480713-757c5ded-c074-4968-9fb6-92706871a726.png)

**Comment by tmarenko** [comment]
Checked 3.1 version of the game, 1920x1080, running with admin privileges
```
Found Tesseract data for 'eng' language at tessdata/eng.traineddata
Initialized Tesseract API with 'eng' language.
Waiting for GenshinImpact.exe process.
Ready for Paimon!
Paimon, shut up!
Unmuting the game.
Paimon, shut up!
Unmuting the game.
Paimon, shut up!
Unmuting the game.
```
![image](https://user-images.githubusercontent.com/31345208/194481732-47358047-31d2-4278-9450-3cb5b1e47b65.png)

**Comment by tmarenko** [comment]
Yeah looks like dialogue box changes its position when using controller. Though script still worked for me with red box
```
Found Tesseract data for 'eng' language at tessdata/eng.traineddata
Initialized Tesseract API with 'eng' language.
Waiting for GenshinImpact.exe process.
Ready for Paimon!
Paimon, shut up!
Unmuting the game.
```
![image](https://user-images.githubusercontent.com/31345208/194482402-c516da43-7d4a-47de-981b-253c6ca24778.png)

**Comment by noRynx** [comment]
> Well it seems a bit off because usually it supposed to be in the green box. Does it show anything it the black box in the top left corner? Example: ![image](https://user-images.githubusercontent.com/31345208/194480713-757c5ded-c074-4968-9fb6-92706871a726.png)

nope it doesnt show that paimon for me

**Comment by tmarenko** [comment]
> nope it doesnt show that paimon for me

You need to run in the middle of the dialogue too. 
If it's still black then try this build: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/3230134657
Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/8725581120/artifacts/394554248

Also please try this old release too: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/releases/tag/1.1.1
It used different function to capture game screen, maybe this was the issue

**Comment by noRynx** [comment]
> > nope it doesnt show that paimon for me
> 
> You need to run in the middle of the dialogue too. If it's still black then try this build: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/3230134657 Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/8725581120/artifacts/394554248
> 
> Also please try this old release too: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/releases/tag/1.1.1 It used different function to capture game screen, maybe this was the issue

![image](https://user-images.githubusercontent.com/47905589/195474417-f5e17b01-0007-4b58-8246-d1948c742d20.png)
yep just black box no paimon text

old release didnt work either and btw im on windows 11 pro 22h2 if it aint compatible for me

**Comment by tmarenko** [comment]
> im on windows 11 pro 22h2 if it aint compatible for me

Unfortunately I don't have a spare PC to install Windows 11 and test it. I've tried it in VM and it failed to run Genshin.

I made another debug build: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/actions/runs/3263216633
Download link: https://github.com/tmarenko/GenshinImpact_PaimonShutUp/suites/8804877746/artifacts/400517911

Should show something like this:
![image](https://user-images.githubusercontent.com/31345208/196120405-47c712bd-9947-4cf9-86e4-e8364c6d8aaf.png)

**Comment by tmarenko** [comment]
No response
